<?xml version="1.0" encoding="utf-8"?><Database Name="gamedb" Class="clientDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\gamedb.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="Client.Properties.Settings" SettingsPropertyName="gamedbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TblGames" Member="TblGames">
    <Type Name="TblGame">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Winner" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Board" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblPosition" Member="TblPositions" ThisKey="Id" OtherKey="GameId" Type="TblPosition" />
    </Type>
  </Table>
  <Table Name="dbo.TblPositions" Member="TblPositions">
    <Type Name="TblPosition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="x" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GameId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblGame_TblPosition" Member="TblGame" ThisKey="GameId" OtherKey="Id" Type="TblGame" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>